od: od-update: Make OD beta -> OD beta upgrade working

diff --git a/board/opendingux/target_skeleton/usr/sbin/od-update b/board/opendingux/target_skeleton/usr/sbin/od-update
--- a/board/opendingux/target_skeleton/usr/sbin/od-update
+++ b/board/opendingux/target_skeleton/usr/sbin/od-update
@@ -1,20 +1,29 @@
 #!/bin/sh
 
-if [ $# -ne 1 ]; then
+if [ $# -lt 1 ]; then
 	echo -e "Incorrect number of parameters.
 Usage:
-\t$0 <data_dir>"
+\t$0 <data_dir> [device]"
 	exit 1
 fi
 
-if [ -z "$FORCE_DEVICE" ]; then
-	DEVICE=$(thisdevice --detect)
-	[ -z "$DEVICE" ] && DEVICE=undetected
+if [ -x ./thisdevice ]; then
+	THISDEVICE=./thisdevice
 else
-	DEVICE="$FORCE_DEVICE"
+	THISDEVICE=$(which thisdevice 2> /dev/null)
 fi
 
-DEVICEINFO=$(thisdevice --device "$DEVICE" 2> /dev/null)
+if [ -z "$THISDEVICE" ]; then
+	echo "thisdevice utility can't be found"
+	exit 12
+fi
+
+[ -z "$DEVICE" ] && DEVICE=$2
+[ -z "$DEVICE" -a -r /tmp/_force_thisdevice ] && DEVICE=$(cat /tmp/_force_thisdevice)
+[ -z "$DEVICE" ] && DEVICE=$($THISDEVICE --detect)
+[ -z "$DEVICE" ] && DEVICE=undetected
+
+DEVICEINFO=$($THISDEVICE --device "$DEVICE" 2> /dev/null)
 if [ $? -ne 0 ] ; then
 	echo "Unknown device $DEVICE"
 	exit 12
@@ -26,13 +35,13 @@ BOOTLD=$1/ubiboot-$DEVICE_BOOTLOADER.bin
 DEVICETREE=$1/$DEVICE_DEVICETREE.dtb
 
 if [ ! -r "$BOOTLD" ]; then
-	echo "Bootloader $2 does not exists"
+	echo "Bootloader $DEVICE_BOOTLOADER does not exists"
 	exit 13
 fi
 
 [ ! -r $DEVICETREE ] && DEVICETREE=/sys/firmware/fdt
 if [ ! -r "$DEVICETREE" ]; then
-	echo "Device tree $3 does not exists"
+	echo "Device tree $DEVICE_DEVICETREE does not exists"
 	exit 14
 fi
 
@@ -99,7 +108,7 @@ if [ -r $ROOTFS -a "$0" != "/tmp/od-update" ] ; then
 			umount $MNT
 
 			# Run the updated od-update script from the rootfs
-			exec /tmp/od-update $*
+			exec /tmp/od-update "$@"
 		else
 			umount $MNT
 		fi
